from building import *

cwd     = GetCurrentDir()

src = Split('''
main.c
''')

if GetDepend(['BSP_USING_SPI_LCD']):
    src += ['lcd_index.c']

if GetDepend(['PKG_USING_NRF24L01']):
    src += ['nrf24l01_init.c']
    
src += ['iotb_event.c']
src += ['iotb_key_process.c']
src += ['iotb_lcd_process.c']

CPPPATH = [str(Dir('#')), cwd]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
